<?php $brand  = $this->getBrand(); ?>
<div class="mage360-brands-wrapper">
    <div class="brand">
        <div class="brand-img">
            <?php  if(is_null ($brand) ==false && !empty($brand->getLogoPathUrl())): ?>
                <img src="<?php echo $brand->getLogoPathUrl(); ?>" alt="<?php echo $brand->getName(); ?>" />
            <?php endif; ?>
        </div>
        <div class="brand-desc">
            <?php  if(is_null ($brand) ==false: ?>
            <?php echo $brand->getDescription(); ?>
            <?php endif; ?>			
        </div>
        <div class="clearfix"></div>
    </div>
</div>
